# Generated by Django 4.1.5 on 2023-01-06 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=2555)),
                ('instagram', models.CharField(max_length=2555)),
                ('pinterest', models.CharField(max_length=2555)),
                ('driblee', models.CharField(max_length=2555)),
            ],
        ),
    ]
