# Generated by Django 4.1.5 on 2023-01-06 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_products_info_products_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products_bed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('despictions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products_sofa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('despictions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Products_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('bonus', models.IntegerField(default=0)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('despictions', models.TextField()),
            ],
        ),
    ]
