# Generated by Django 4.1.5 on 2023-01-06 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_products_bed_products_sofa_products_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='banner',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
