# Generated by Django 4.1.5 on 2023-01-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_app_email_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_store',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='app',
            name='google_play',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
