# Generated by Django 4.1.5 on 2023-01-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_info_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='company_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
