# Generated by Django 4.1.5 on 2023-01-06 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_clothe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothes',
            old_name='img',
            new_name='img1',
        ),
        migrations.AddField(
            model_name='clothes',
            name='img2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothes',
            name='img3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
