# Generated by Django 4.1.5 on 2023-01-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_rename_img_clothes_img1_clothes_img2_clothes_img3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Related_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=255)),
                ('despictions', models.CharField(max_length=255)),
                ('bonus', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
        ),
    ]
