# Generated by Django 4.1.5 on 2023-01-08 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_shop_width'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Related_Products',
        ),
    ]
