# Generated by Django 4.1.5 on 2023-01-08 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
