# Generated by Django 4.1.5 on 2023-01-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Best_forever',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
                ('img', models.ImageField(upload_to='')),
                ('video', models.CharField(max_length=266666)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='about_width',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
